# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5827cb173bb85f0e45238bd8db68d7322fcf2be0014cd904e41064ac113d8ce8c9c40c1c328f02cd0ba9c0c46c06cf1ff175bf0299ca422cb84dc4251acac3

test:
  secret_key_base: ec12aadb30b06dadf74256121223cde911f2f598d58cd4a0bb257bf05530da1e1f0e5f8f5332242cdb23052a97d9534e60a72eba132c1f5601b4bf5b981a62d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
